const Productdata = [
  {
    id: 1,
    title: "Fibaro Motion Sensor",
    imgsrc: "/images/products/Motion_Sensor_Right.png",
    producttype: "sensor",
    description: "motion sensor can use to find intruder",
  },
  {
    id: 2,
    title: "Fibaro Door Sensor",
    imgsrc: "/images/products/doorsensor.png",
    producttype: "sensor",
    description: "door sensor can used to secure your doors",
  },
  {
    id: 3,
    title: "Fibaro smoke Sensor",
    imgsrc: "/images/products/smokesensor.png",
    producttype: "sensor",
    description: "smoke sensor can use to find smoke of fire in your home",
  },
  {
    id: 4,
    title: "Fibaro single relay",
    imgsrc: "/images/products/singlerelay.png",
    producttype: "actors",
    description: "can control single light",
  },
  {
    id: 5,
    title: "Fibaro Double relay",
    imgsrc: "/images/products/doublerelay.png",
    producttype: "actors",
    description: "can control double  light",
  },
  {
    id: 6,
    title: "Fibaro dimmer",
    imgsrc: "/images/products/dimmer.png",
    producttype: "actors",
    description: "dimmer is used to dim your lights",
  },
  {
    id: 7,
    title: "Fibaro roller shutter",
    imgsrc: "/images/products/rollershutter.png",
    producttype: "actors",
    description: "roller shutter used to open blinds remotely",
  },
  {
    id: 8,
    title: "Fibaro RGBW",
    imgsrc: "/images/products/rgbwcontroller.png",
    producttype: "actors",
    description: "used to set color of your room",
  },
  {
    id: 9,
    title: "Fibaro keyfob",
    imgsrc: "/images/products/keyfob.jpg",
    producttype: "remote",
    description: "motion sensor can use to find intruder",
  },
  {
    id: 10,
    title: "Fibaro Emergency button",
    imgsrc: "/images/products/emergencybutton.png",
    producttype: "remote",
    description: "motion sensor can use to find intruder",
  },
  {
    id: 11,
    title: "Fibaro Homecenter 2",
    imgsrc: "/images/products/hc2.png",
    producttype: "gateway",
    description: "motion sensor can use to find intruder",
  },
  {
    id: 12,
    title: "Fibaro Homecenter lite",
    imgsrc: "/images/products/hcl.png",
    producttype: "gateway",
    description: "motion sensor can use to find intruder",
  },
];
export default Productdata;
